type NodeArgon2 = typeof import('@node-rs/argon2')

let nodeArgon2: Promise<NodeArgon2> | undefined

function isBunRuntime() {
  return typeof process !== 'undefined' && Boolean(process.versions?.bun)
}

function loadNodeArgon2() {
  return (nodeArgon2 ??= import('@node-rs/argon2'))
}

export function hashPassword(password: string) {
  if (isBunRuntime()) {
    return Bun.password.hash(password, { algorithm: 'argon2id' })
  }

  // Vercel runs the API on Node, where Bun.password is unavailable. Use a
  // standards-compatible Argon2id implementation so hashes are portable
  // between local Bun development and the production runtime.
  return loadNodeArgon2().then(({ hash }) => hash(password, { algorithm: 2 }))
}

export async function verifyPassword(password: string, passwordHash: string) {
  if (passwordHash.startsWith('$argon2')) {
    if (isBunRuntime()) return Bun.password.verify(password, passwordHash)

    const { verify } = await loadNodeArgon2()
    return verify(passwordHash, password)
  }

  // Legacy Node hashes generated by the pre-Argon2 compatibility shim are
  // still verified through Bun.password (the shim implements this format).
  return Bun.password.verify(password, passwordHash)
}
